# Directory and File Paths
paths:
  raw_data: "data/raw/SampleData.json.gz"
  processed_dir: "data/processed"
  model_save: "model/srars_best_model.h5"

# Model Architecture Parameters
model:
  num_heads: 8
  key_dim: 128
  dff: 2048
  dropout_rate: 0.1
  epsilon: 1e-6

# Training Hyperparameters
train:
  batch_size: 64
  epochs: 50
  learning_rate: 0.001
  patience: 5